### ISSUE TITLE
matrix SVD decomposition is not working

### ISSUE THREAD

**Issue by LucaTedeschini** [gameticharles/matrix_utils#1]
I recently installed this package specifically because i needed a quick way to compute the SVD decomposition of a matrix, but it seems like that it doesn't work correctly. This is the code i used

```dart
void main() {
  Matrix mat = Matrix.fromList([
    [3, 2, 2],
    [2, 3, -2]
  ]);

  var svd = mat.decomposition.singularValueDecomposition();
}
```

which raises the following exception

```
Exception: Matrices have different shapes
#0      MatrixManipulationExtension.copyFrom (package:matrix_utils/src/extension/manipulate.dart:677:9)
#1      new SVD (package:matrix_utils/src/extension/decomposition/svd.dart:58:9)
#2      MatrixDecomposition.singularValueDecomposition (package:matrix_utils/src/extension/decomposition/decomposition.dart:696:15)
#3      main (file:///.../helloworld.dart:17:31)
#4      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#5      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```
I also tried the code written in the documentation
```dart
Matrix A = Matrix.fromList([
[3, 2, 2],
[2, 3, -2]
]);

SVD svd = A.singularValueDecomposition();
```

but it doesn't work either (it raises the same exception). Am i doing something wrong or there is a problem in the library?

By the way, thank you for this package, it's cutting of half of the work i need to do

**Comment by gameticharles** [comment]
@LucaTedeschini, thanks for reaching out!

The `matrix_utils` library has been on hold for a while. In the meantime, you might want to try **[advance_math](https://pub.dev/packages/advance_math)**, a more robust library I’ve developed. It includes all the functionality of `matrix_utils` and more, and it could potentially resolve the issue you're encountering.

Let me know if you have any questions or need further assistance!
